//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Entradas.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Entradas: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Entradas()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Entradas"",
    ""maps"": [
        {
            ""name"": ""Acciones"",
            ""id"": ""e14288ab-9318-4dc5-ac94-ef116d0986e2"",
            ""actions"": [
                {
                    ""name"": ""Parálisis"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8b852639-7133-4477-b677-0856017b8cb7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b0262b11-8bff-4b87-b0c5-b69e5c4e7a1e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Parálisis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Acciones
        m_Acciones = asset.FindActionMap("Acciones", throwIfNotFound: true);
        m_Acciones_Parálisis = m_Acciones.FindAction("Parálisis", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Acciones
    private readonly InputActionMap m_Acciones;
    private List<IAccionesActions> m_AccionesActionsCallbackInterfaces = new List<IAccionesActions>();
    private readonly InputAction m_Acciones_Parálisis;
    public struct AccionesActions
    {
        private @Entradas m_Wrapper;
        public AccionesActions(@Entradas wrapper) { m_Wrapper = wrapper; }
        public InputAction @Parálisis => m_Wrapper.m_Acciones_Parálisis;
        public InputActionMap Get() { return m_Wrapper.m_Acciones; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AccionesActions set) { return set.Get(); }
        public void AddCallbacks(IAccionesActions instance)
        {
            if (instance == null || m_Wrapper.m_AccionesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AccionesActionsCallbackInterfaces.Add(instance);
            @Parálisis.started += instance.OnParálisis;
            @Parálisis.performed += instance.OnParálisis;
            @Parálisis.canceled += instance.OnParálisis;
        }

        private void UnregisterCallbacks(IAccionesActions instance)
        {
            @Parálisis.started -= instance.OnParálisis;
            @Parálisis.performed -= instance.OnParálisis;
            @Parálisis.canceled -= instance.OnParálisis;
        }

        public void RemoveCallbacks(IAccionesActions instance)
        {
            if (m_Wrapper.m_AccionesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAccionesActions instance)
        {
            foreach (var item in m_Wrapper.m_AccionesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AccionesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AccionesActions @Acciones => new AccionesActions(this);
    public interface IAccionesActions
    {
        void OnParálisis(InputAction.CallbackContext context);
    }
}
