//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/SprintMovement.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SprintMovement: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SprintMovement()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SprintMovement"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""73915070-a0d7-4406-8512-1df001554dfc"",
            ""actions"": [
                {
                    ""name"": ""StartSprint"",
                    ""type"": ""Button"",
                    ""id"": ""a7e16b96-ddaf-4239-923a-ad0d1337e514"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StopSprint"",
                    ""type"": ""Button"",
                    ""id"": ""cd602010-1578-40f4-8e64-010a0134cfaf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b1df4b76-0bc7-4cfa-993c-ef59e230c171"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartSprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3b0d417-2aec-4e2a-bb2c-9c6292dc1d99"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StopSprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_StartSprint = m_Player.FindAction("StartSprint", throwIfNotFound: true);
        m_Player_StopSprint = m_Player.FindAction("StopSprint", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_StartSprint;
    private readonly InputAction m_Player_StopSprint;
    public struct PlayerActions
    {
        private @SprintMovement m_Wrapper;
        public PlayerActions(@SprintMovement wrapper) { m_Wrapper = wrapper; }
        public InputAction @StartSprint => m_Wrapper.m_Player_StartSprint;
        public InputAction @StopSprint => m_Wrapper.m_Player_StopSprint;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @StartSprint.started += instance.OnStartSprint;
            @StartSprint.performed += instance.OnStartSprint;
            @StartSprint.canceled += instance.OnStartSprint;
            @StopSprint.started += instance.OnStopSprint;
            @StopSprint.performed += instance.OnStopSprint;
            @StopSprint.canceled += instance.OnStopSprint;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @StartSprint.started -= instance.OnStartSprint;
            @StartSprint.performed -= instance.OnStartSprint;
            @StartSprint.canceled -= instance.OnStartSprint;
            @StopSprint.started -= instance.OnStopSprint;
            @StopSprint.performed -= instance.OnStopSprint;
            @StopSprint.canceled -= instance.OnStopSprint;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnStartSprint(InputAction.CallbackContext context);
        void OnStopSprint(InputAction.CallbackContext context);
    }
}
